version: '3'

services:
  api:
    build: ./api
    command: bash -c 'tail -f /dev/null'
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    volumes:
      - ./api:/studyante-app/api
    build: ./api
