# Generated by Django 2.2.7 on 2019-11-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='subject',
            field=models.CharField(choices=[('MATH', 'MATH'), ('FILIPINO', 'FILIPINO'), ('ENGLISH', 'ENGLISH'), ('SCIENCE', 'SCIENCE'), ('AP', 'AP'), ('TLE', 'TLE'), ('CE', 'CE'), ('COMPUTER', 'COMPUTER'), ('MAPEH', 'MAPEH')], max_length=32),
        ),
    ]
