# Generated by Django 2.2.7 on 2019-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191123_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
