# Generated by Django 2.2.7 on 2019-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requirement_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=32),
        ),
    ]
